name: shared_preferences_storage
description: Storage implementation using shared_preferences to be used in hydrated_bloc.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  hydrated_bloc: ^10.0.0
  meta: ^1.15.0
  shared_preferences: ^2.5.3
  synchronized: ^3.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
